// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeA4RjmImpk2N9owBBRu8FiEqxBcbpJ3g',
    appId: '1:139197430152:web:f7384e7fdf5cb5c081223d',
    messagingSenderId: '139197430152',
    projectId: 'firstproject-c30de',
    authDomain: 'firstproject-c30de.firebaseapp.com',
    storageBucket: 'firstproject-c30de.appspot.com',
    measurementId: 'G-ZBW4W4XC1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVN8ApUcHyzgBsRPCp1nRyDw-6_3s2cZM',
    appId: '1:139197430152:android:2c8686d816b4f8ba81223d',
    messagingSenderId: '139197430152',
    projectId: 'firstproject-c30de',
    storageBucket: 'firstproject-c30de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASVyNKvwTig39SUJT9E4OrduZw3heiXzs',
    appId: '1:139197430152:ios:98baec5dc590b55081223d',
    messagingSenderId: '139197430152',
    projectId: 'firstproject-c30de',
    storageBucket: 'firstproject-c30de.appspot.com',
    iosBundleId: 'com.abhishek.krishna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASVyNKvwTig39SUJT9E4OrduZw3heiXzs',
    appId: '1:139197430152:ios:98baec5dc590b55081223d',
    messagingSenderId: '139197430152',
    projectId: 'firstproject-c30de',
    storageBucket: 'firstproject-c30de.appspot.com',
    iosBundleId: 'com.abhishek.krishna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeA4RjmImpk2N9owBBRu8FiEqxBcbpJ3g',
    appId: '1:139197430152:web:2dcf75ba547a9faa81223d',
    messagingSenderId: '139197430152',
    projectId: 'firstproject-c30de',
    authDomain: 'firstproject-c30de.firebaseapp.com',
    storageBucket: 'firstproject-c30de.appspot.com',
    measurementId: 'G-905QN3RFVY',
  );
}
